name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: ./build.sh
      - name: Save output files in /docs to main branch
        run: git add -A
      - run: git config --local user.email "action@github.com"
      - run: git config --local user.name "GitHub Action"
      - run: git commit -m 'Deploy static website to docs/'
      - run: git push